<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="9.0.5" />
		<PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="9.0.5" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.3.0" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Cors" Version="2.3.0" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Localization" Version="2.3.0" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Razor" Version="2.3.0" />
		<PackageReference Include="Microsoft.FluentUI.AspNetCore.Components" Version="4.12.0" />
		<PackageReference Include="Microsoft.FluentUI.AspNetCore.Components.Emoji" Version="4.12.0" />
		<PackageReference Include="Microsoft.FluentUI.AspNetCore.Components.Icons" Version="4.12.0" />
		<PackageReference Include="System.Net.Http" Version="4.3.4" />
		<PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
		<PackageReference Include="Toolbelt.Blazor.HttpClientInterceptor" Version="10.2.0" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\..\FoodShopBilling.Application\FoodShopBilling.Application.csproj" />
	</ItemGroup>

	

</Project>